name: news
description: "Newsify"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  localization:
  intl: any
  dio: ^5.0.1
  either_dart:
  pretty_dio_logger: ^1.3.1
  flutter_svg:
  package_info_plus: ^3.0.3
  curl_logger_dio_interceptor: ^1.0.0
  go_router: ^14.0.2
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_sizer: ^1.0.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^4.0.3
  lottie:
  path_provider: ^2.1.3
  mockito: ^5.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/json/
    - assets/img/